bin:
  link: "~/.bin"

chunkwm:
  prelink: 
    - "brew tap koekeishiya/formulae"
  link: "~"
  dependencies:
    - "chunkwm"
    - "koekeishiya/formulae/skhd"
  postlink:
    - "brew services start chunkwm"
    - "brew services start skhd"

flake8:
  link: "~/.config"

git:
  link: "~"

kitty:
  prelink:
    - "brew cask install kitty"
  link: "~/.config/kitty"

ranger:
  link: "~/.config/ranger"
  dependencies:
    - "ranger"
    - "imagemagick"
    - "w3m"
    - "feh"

system:
  link: "~"

vim:
  link:
    - minisnip: "~/.vim"
    - after: "~/.vim"
    - "*": "~"
    - ".*": "~"
  dependencies:
    - "vim"
    - "curl"
    - "ctags"
    - "pandoc"
    - "python3"
    - "python-pip"
    - "the_silver_searcher"
  postlink:
    - "mkdir -p ~/.vim/undo"
    - "mkdir -p ~/.vim/backup"
